# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='type',
            field=models.CharField(default='none', max_length=64),
            preserve_default=False,
        ),
    ]
