# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_flag_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('session_key', 'photo')]),
        ),
    ]
